notifications:
  slack: zewo:VjyVCCQvTOw9yrbzQysZezD1
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.3
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/Zewo/Zewo/master/Scripts/Travis/install.sh)"

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install zewo/tap/libdill; fi

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo "deb [trusted=yes] http://apt.zewo.io ./" | sudo tee --append /etc/apt/sources.list; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libdill; fi

  - export LD_LIBRARY_PATH=/usr/local/lib
script:
  - bash <(curl -s https://raw.githubusercontent.com/Zewo/Zewo/master/Scripts/Travis/build-test.sh) Venice
after_success:
  - bash <(curl -s https://raw.githubusercontent.com/Zewo/Zewo/master/Scripts/Travis/report-coverage.sh)
